### ISSUE TITLE
Support for net4.8?

### ISSUE THREAD

**Issue by seghier** [StirlingLabs/Assimp.Net#6]
Hi
Can you please add support for net4.8?

The previous version of **Assimp 4.1.0 of Nicholas Woodfield** works fine but it is old and can't read many new formats.

**Comment by Rjvs** [comment]
No, I'm sorry.  The goal for this fork is to only support modern C#. Nicholas is doing a fine job maintaining support for older versions and is modernising his code base within those restrictions.

**Comment by seghier** [comment]
Sadly , there are many softwares don't support new .Net like Rhino

**Comment by Rjvs** [comment]
https://developer.rhino3d.com/guides/rhinocommon/moving-to-dotnet-7/

**Comment by seghier** [comment]
Yes but not nuget pacakge for visual studio and Rhino 8 is still beta version

**Comment by seghier** [comment]
After many tests i success to make it work but why  assimp dll don't copied automatically to the folder with the compiled solution?
I copy it manually but the plugin don't work unlike the one of **Nicholas Woodfield** works perfect

![image](https://github.com/StirlingLabs/Assimp.Net/assets/6026588/73254eac-0c49-4f34-92d7-8b17df515c1c)
